### ISSUE TITLE
Add Average Indoor Temp and Outdoor Temp?

### ISSUE THREAD

**Issue by idoiten** [LordMike/MBW.Uponor2MQTT#1]
Hi,

Thank you for your effort in this. It's working great. Is it possible to add the ability to read the Average Indoor Temp and the Current Outdoor Temp that is stated on the main page in the Uponor GUI?

![image](https://user-images.githubusercontent.com/71437044/107198290-36aacf80-69f5-11eb-8303-4fdbe9af62dd.png)

Best regards

**Comment by LordMike** [comment]
I don't have an outdoor sensor, but let's see.

In my excel sheet, we can see the values that the Uponor thingy can provide.
For outdoor temperature, there is a value for each controller (I suppose you attach the sensor to a specific controller?)

![image](https://user-images.githubusercontent.com/1027111/107212460-46cbaa80-6a07-11eb-8629-1ce8c68771bf.png)

I can also see that there is a system-wide average value for temperature:

![image](https://user-images.githubusercontent.com/1027111/107212507-577c2080-6a07-11eb-93de-fc4dc4447c6b.png)

**Comment by LordMike** [comment]
So if I add a sensor for each outdoor value from each controller you have... and then a sensor for the value no. 37.

**Comment by idoiten** [comment]
I think that would be perfect. For me I only have one controller, so object id 67 should be enough for the outdoor temperature.

**Comment by LordMike** [comment]
Ok. So I'm going to try to use the Outdoor Sensor Presence to detect if I should make the sensor. We'll see how it works out (as I don't have the ability to test it...) :)

**Comment by LordMike** [comment]
@idoiten a `:dev` image should be available shortly.

**Comment by idoiten** [comment]
Wow, great. Just tested it and it works like a dream. :)
Thanks!

![image](https://user-images.githubusercontent.com/71437044/107375051-9d5ce580-6ae8-11eb-8529-80f58920161f.png)
![image](https://user-images.githubusercontent.com/71437044/107375112-abab0180-6ae8-11eb-8912-c0c7416c72c2.png)
